/**
 * History data loader
 * Load work item update history for deep metrics analysis
 */

import fs from 'fs';
import { WorkItemUpdate } from '../types.js';

/**
 * Load work item update history from JSON file
 * This file is generated by azure-devops-batch skill's fetch-work-item-history.ts
 */
export function loadWorkItemHistory(filePath: string): WorkItemUpdate[] {
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  History file not found: ${filePath}`);
    console.warn('   Deep metrics (time-in-state, daily-wip, flow-efficiency) will be skipped.');
    console.warn('   To enable: Run fetch-work-item-history.ts from azure-devops-batch skill first.');
    return [];
  }

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const data = JSON.parse(content);

    // Handle different possible formats
    if (Array.isArray(data)) {
      return data as WorkItemUpdate[];
    } else if (data.value && Array.isArray(data.value)) {
      return data.value as WorkItemUpdate[];
    } else if (data.updates && Array.isArray(data.updates)) {
      return data.updates as WorkItemUpdate[];
    } else {
      console.warn('⚠️  Unknown history file format');
      return [];
    }
  } catch (error) {
    console.error(`❌ Error loading history file: ${error}`);
    return [];
  }
}

/**
 * Check if history data is available
 */
export function hasHistoryData(filePath: string): boolean {
  return fs.existsSync(filePath);
}

/**
 * Get default history file path based on work items file path
 */
export function getDefaultHistoryPath(workItemsPath: string): string {
  // Assuming structure: data/july_november_2025/all_work_items.json
  // History would be at: data/july_november_2025/history_detailed/all_work_item_updates.json

  const dir = workItemsPath.substring(0, workItemsPath.lastIndexOf('/'));
  return `${dir}/history_detailed/all_work_item_updates.json`;
}
