/**
 * History data loader
 * Load work item update history for deep metrics analysis
 */

import fs from 'fs';
import { WorkItemUpdate } from '../types.js';
import { Result, Ok, Err } from './result.js';

/**
 * Represents different error states when loading history
 */
export enum HistoryLoadError {
  NOT_FOUND = 'NOT_FOUND',
  PARSE_ERROR = 'PARSE_ERROR',
  INVALID_FORMAT = 'INVALID_FORMAT',
  FILE_ERROR = 'FILE_ERROR',
}

/**
 * Extended error for history loading with specific error code
 */
export class HistoryError extends Error {
  constructor(
    public code: HistoryLoadError,
    message: string
  ) {
    super(message);
    this.name = 'HistoryError';
  }
}

/**
 * Load work item update history from JSON file
 * This file is generated by azure-devops-batch skill's fetch-work-item-history.ts
 * Returns Result type: Ok(WorkItemUpdate[]) on success, Err(HistoryError) on failure
 */
export function loadWorkItemHistory(
  filePath: string
): Result<WorkItemUpdate[], HistoryError> {
  try {
    if (!fs.existsSync(filePath)) {
      return Err(
        new HistoryError(
          HistoryLoadError.NOT_FOUND,
          `History file not found: ${filePath}. Deep metrics will be unavailable.`
        )
      );
    }

    const content = fs.readFileSync(filePath, 'utf-8');

    let data: any;
    try {
      data = JSON.parse(content);
    } catch (parseError) {
      return Err(
        new HistoryError(
          HistoryLoadError.PARSE_ERROR,
          `Failed to parse history JSON from ${filePath}: ${
            parseError instanceof Error ? parseError.message : String(parseError)
          }`
        )
      );
    }

    // Handle different possible formats
    let updates: WorkItemUpdate[];

    if (Array.isArray(data)) {
      updates = data as WorkItemUpdate[];
    } else if (data.value && Array.isArray(data.value)) {
      updates = data.value as WorkItemUpdate[];
    } else if (data.updates && Array.isArray(data.updates)) {
      updates = data.updates as WorkItemUpdate[];
    } else {
      return Err(
        new HistoryError(
          HistoryLoadError.INVALID_FORMAT,
          `Unknown history file format. Expected array or object with 'value'/'updates' property.`
        )
      );
    }

    if (updates.length === 0) {
      return Err(
        new HistoryError(
          HistoryLoadError.INVALID_FORMAT,
          `History file is empty (contains no work item updates)`
        )
      );
    }

    return Ok(updates);
  } catch (error) {
    return Err(
      new HistoryError(
        HistoryLoadError.FILE_ERROR,
        `Error loading history file from ${filePath}: ${
          error instanceof Error ? error.message : String(error)
        }`
      )
    );
  }
}

/**
 * Check if history data is available
 */
export function hasHistoryData(filePath: string): boolean {
  return fs.existsSync(filePath);
}

/**
 * Get default history file path based on work items file path
 */
export function getDefaultHistoryPath(workItemsPath: string): string {
  // Assuming structure: data/july_november_2025/all_work_items.json
  // History would be at: data/july_november_2025/history_detailed/all_work_item_updates.json

  const dir = workItemsPath.substring(0, workItemsPath.lastIndexOf('/'));
  return `${dir}/history_detailed/all_work_item_updates.json`;
}
